# Generated by Django 5.0.4 on 2024-05-26 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='plan_hours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='H-EP2RHX', max_length=10, unique=True, verbose_name='Code')),
                ('date_day', models.DateField(verbose_name='Day')),
                ('start_hours', models.TimeField(verbose_name='Start')),
                ('end_hours', models.TimeField(verbose_name='Start')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employe')),
            ],
            options={
                'verbose_name': 'Hours of Work',
                'verbose_name_plural': 'Hours of Work',
            },
        ),
    ]
