# Generated by Django 5.0.4 on 2024-05-29 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Hours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan_hours',
            name='code',
            field=models.CharField(default='H-PS44S8', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='plan_hours',
            name='end_hours',
            field=models.TimeField(verbose_name='End'),
        ),
        migrations.CreateModel(
            name='Disponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='D-LZOFXH', max_length=10, unique=True, verbose_name='Code')),
                ('date_day', models.DateField(verbose_name='Day')),
                ('Date_creation', models.DateField(verbose_name='Day of Creation')),
                ('start_hours', models.TimeField(verbose_name='Start')),
                ('end_hours', models.TimeField(verbose_name='End')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employe')),
            ],
            options={
                'verbose_name': 'Disponibility of Employee',
                'verbose_name_plural': 'Disponibilities of Employees',
            },
        ),
    ]
