# Generated by Django 5.0.4 on 2024-05-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Hours', '0002_alter_plan_hours_code_alter_plan_hours_end_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibility',
            name='code',
            field=models.CharField(default='D-UC8ZPP', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='plan_hours',
            name='code',
            field=models.CharField(default='H-QPF9BK', max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
