# Generated by Django 5.0.4 on 2024-05-29 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Hours', '0003_alter_disponibility_code_alter_plan_hours_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibility',
            name='Status',
            field=models.CharField(default='waiting', max_length=10, unique=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='disponibility',
            name='Date_creation',
            field=models.DateField(default=datetime.date(2024, 5, 29), verbose_name='Day of Creation'),
        ),
        migrations.AlterField(
            model_name='disponibility',
            name='code',
            field=models.CharField(default='D-5ZFMEC', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='plan_hours',
            name='code',
            field=models.CharField(default='H-2RGBLS', max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
