# Generated by Django 5.0.4 on 2024-05-29 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Hours', '0004_disponibility_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibility',
            name='Date_creation',
            field=models.DateField(default=datetime.datetime(2024, 5, 29, 16, 6, 59, 48753), verbose_name='Day of Creation'),
        ),
        migrations.AlterField(
            model_name='disponibility',
            name='code',
            field=models.CharField(default='D-PEASC5', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='plan_hours',
            name='code',
            field=models.CharField(default='H-H786MH', max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
