# Generated by Django 5.0.4 on 2024-06-16 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Hours', '0007_alter_disponibility_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibility',
            name='Date_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 16, 1, 57, 27, 849507), verbose_name='Day of Creation'),
        ),
        migrations.AlterField(
            model_name='disponibility',
            name='code',
            field=models.CharField(default='D-1XRPSQ', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='plan_hours',
            name='code',
            field=models.CharField(default='H-NMGUJI', max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
