# Generated by Django 5.0.4 on 2024-06-16 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Hours', '0011_alter_disponibility_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibility',
            name='Date_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 16, 12, 23, 10, 284610), verbose_name='Day of Creation'),
        ),
        migrations.AlterField(
            model_name='disponibility',
            name='code',
            field=models.CharField(default='D-Q7XEVH', max_length=10, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='plan_hours',
            name='code',
            field=models.CharField(default='H-FPWPCT', max_length=10, unique=True, verbose_name='Code'),
        ),
    ]
