# Generated by Django 5.0.4 on 2024-06-16 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Hours', '0019_alter_disponibility_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibility',
            name='Date_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 16, 14, 51, 11, 406804), verbose_name='Day of Creation'),
        ),
    ]
