# Generated by Django 4.2.13 on 2024-06-29 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Hours', '0020_alter_disponibility_date_creation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibility',
            name='Date_creation',
            field=models.DateField(default=datetime.datetime(2024, 6, 29, 13, 22, 54, 51646), verbose_name='Day of Creation'),
        ),
    ]
