# Generated by Django 5.0.4 on 2024-04-27 05:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('disponibility_date', models.DateField(verbose_name='Disponibility Date')),
                ('start_hour', models.TimeField(verbose_name='Start Hour')),
                ('end_hour', models.TimeField(verbose_name='End Hour')),
                ('duration', models.DurationField(verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Disponibility',
                'verbose_name_plural': 'Disponibilities',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('Wording', models.CharField(max_length=30, unique=True, verbose_name='Wording')),
                ('Description', models.TextField(max_length=500, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('creation_date', models.DateTimeField(verbose_name='Creation Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('start_hour', models.TimeField(verbose_name='Start Hour')),
                ('end_hour', models.TimeField(verbose_name='End Hour')),
                ('Comment', models.CharField(max_length=500, unique=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=30, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='E-mail')),
                ('admin', models.BooleanField(default=False, verbose_name='Administrator')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Account.service', verbose_name='Service')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('status', models.CharField(max_length=30, unique=True, verbose_name='Status')),
                ('reason', models.CharField(max_length=30, unique=True, verbose_name='Reason')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Beneficiary')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(max_length=30, unique=True, verbose_name='Status')),
                ('duration', models.DurationField(verbose_name='Duratiion')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Beneficiary')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='Departure_resquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('departure_date', models.DateField(verbose_name='Departure Date')),
                ('return_date', models.DateField(verbose_name='Return Date')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('status', models.CharField(max_length=30, unique=True, verbose_name='Status')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Beneficiary')),
            ],
            options={
                'verbose_name': 'Departure Resquest',
                'verbose_name_plural': 'Departure Resquests',
            },
        ),
    ]
