# Generated by Django 5.0.4 on 2024-05-29 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_alter_user_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disponibility',
        ),
    ]
