# Generated by Django 5.0.4 on 2024-06-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_delete_disponibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='permission',
            name='beneficiary',
        ),
        migrations.DeleteModel(
            name='Departure_resquest',
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
