# Generated by Django 4.2.13 on 2024-06-29 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_remove_holiday_beneficiary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('RH', 'RH')], default=None, max_length=10, verbose_name='Rôle'),
        ),
    ]
