# Generated by Django 5.0.4 on 2024-06-16 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Holidays', '0002_departure_resquest_holiday_permission_delete_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure_resquest',
            name='code',
            field=models.CharField(default='Dp-ESFJSY', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='code',
            field=models.CharField(default='Ho-TCORCE', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='status',
            field=models.CharField(default='waiting', max_length=30, unique=True, verbose_name='Status'),
        ),
    ]
