# Generated by Django 5.0.4 on 2024-06-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Holidays', '0003_alter_departure_resquest_code_alter_holiday_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure_resquest',
            name='code',
            field=models.CharField(default='Dp-16VTP6', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='code',
            field=models.CharField(default='Ho-HLLXQ9', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='status',
            field=models.CharField(default='waiting', max_length=30, verbose_name='Status'),
        ),
    ]
