# Generated by Django 5.0.4 on 2024-06-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Holidays', '0006_alter_departure_resquest_code_alter_holiday_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure_resquest',
            name='code',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='code',
            field=models.CharField(default='', max_length=30, unique=True, verbose_name='Code'),
        ),
    ]
