# Generated by Django 5.0.4 on 2024-06-16 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Holidays', '0008_alter_permission_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure_resquest',
            name='holiday',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Manage_Holidays.holiday', verbose_name='Holiday'),
            preserve_default=False,
        ),
    ]
