# Generated by Django 5.0.4 on 2024-06-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Manage_Holidays', '0009_departure_resquest_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departure_resquest',
            name='status',
            field=models.CharField(default='waiting', max_length=30, verbose_name='Status'),
        ),
    ]
